languageCode = "en-us"
title = "Dopetrope"
baseURL = "http://localhost:1313/"
theme = "hugo-theme-dopetrope"

[params.portfolio]
    title = "My Portfolio"
    foldername = "portfolio"
    findoutmoretext = "Find out more"

[params.blog]
    title = "The Blog"
    viewalltext = "View All"
    foldername = "blog"

[params.settings]
    googleanalytics = ""
    disqus = ""